<a href="https://colab.research.google.com/github/naveen2139/GUVI-DATA_SCIENCE_B9/blob/main/DataPreprocessing_Assignment11_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

# **Step 1: Importing the libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [3]:
files.upload()

Saving Data.csv to Data.csv


{'Data.csv': b'Country,Age,Salary,Purchased\r\nFrance,44,72000,No\r\nSpain,27,48000,Yes\r\nGermany,30,54000,No\r\nSpain,38,61000,No\r\nGermany,40,,Yes\r\nFrance,35,58000,Yes\r\nSpain,,52000,No\r\nFrance,48,79000,Yes\r\nGermany,50,83000,No\r\nFrance,37,67000,Yes'}

# **Step 2: Importing dataset**

In [4]:
raw_data=pd.read_csv("Data.csv")
raw_data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# **Step 3: Handling the missing data**

In [5]:
raw_data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

**Country**

In [6]:
raw_data.Country.isna().sum()

0

**Age**

In [7]:
raw_data.Age.isnull().sum()

1

In [8]:
raw_data['Age']=raw_data['Age'].fillna(raw_data['Age'].mode())

In [9]:
raw_data.Age.isnull().sum()

0

**Salary**

In [10]:
raw_data.Salary.isnull().sum()

1

In [11]:
raw_data['Salary']=raw_data['Salary'].fillna(raw_data['Salary'].mean())

In [12]:
raw_data.Salary.isnull().sum()

0

**Purchased**

In [13]:
raw_data.Purchased.isnull().sum()

0

# **Step 4: Encoding categorical data**

In [14]:
raw_data

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  44.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [15]:
raw_data.Purchased=raw_data.Purchased.str.lower()
raw_data.Purchased=raw_data.Purchased.str.strip()
raw_data

Country   Age        Salary Purchased
0   France  44.0  72000.000000        no
1    Spain  27.0  48000.000000       yes
2  Germany  30.0  54000.000000        no
3    Spain  38.0  61000.000000        no
4  Germany  40.0  63777.777778       yes
5   France  35.0  58000.000000       yes
6    Spain  44.0  52000.000000        no
7   France  48.0  79000.000000       yes
8  Germany  50.0  83000.000000        no
9   France  37.0  67000.000000       yes

In [16]:
raw_data.Purchased=raw_data.Purchased.map({'no':0,"yes":1})
raw_data

Country   Age        Salary  Purchased
0   France  44.0  72000.000000          0
1    Spain  27.0  48000.000000          1
2  Germany  30.0  54000.000000          0
3    Spain  38.0  61000.000000          0
4  Germany  40.0  63777.777778          1
5   France  35.0  58000.000000          1
6    Spain  44.0  52000.000000          0
7   France  48.0  79000.000000          1
8  Germany  50.0  83000.000000          0
9   France  37.0  67000.000000          1

# **Step 5: Creating a dummy variable**

In [17]:
encoded_data=pd.get_dummies(raw_data,columns=['Country'])
encoded_data

Age        Salary  ...  Country_Germany  Country_Spain
0  44.0  72000.000000  ...                0              0
1  27.0  48000.000000  ...                0              1
2  30.0  54000.000000  ...                1              0
3  38.0  61000.000000  ...                0              1
4  40.0  63777.777778  ...                1              0
5  35.0  58000.000000  ...                0              0
6  44.0  52000.000000  ...                0              1
7  48.0  79000.000000  ...                0              0
8  50.0  83000.000000  ...                1              0
9  37.0  67000.000000  ...                0              0

[10 rows x 6 columns]

In [18]:
encoded_data['Salary']=encoded_data['Salary'].astype('float64')
encoded_data['Age']=encoded_data['Age'].astype('float64')
encoded_data

Age        Salary  ...  Country_Germany  Country_Spain
0  44.0  72000.000000  ...                0              0
1  27.0  48000.000000  ...                0              1
2  30.0  54000.000000  ...                1              0
3  38.0  61000.000000  ...                0              1
4  40.0  63777.777778  ...                1              0
5  35.0  58000.000000  ...                0              0
6  44.0  52000.000000  ...                0              1
7  48.0  79000.000000  ...                0              0
8  50.0  83000.000000  ...                1              0
9  37.0  67000.000000  ...                0              0

[10 rows x 6 columns]

In [19]:
purchased_status=encoded_data.Purchased
encoded_data=encoded_data.drop(['Purchased'],axis=1)
encoded_data['purchased_status']=purchased_status
encoded_data

Age        Salary  ...  Country_Spain  purchased_status
0  44.0  72000.000000  ...              0                 0
1  27.0  48000.000000  ...              1                 1
2  30.0  54000.000000  ...              0                 0
3  38.0  61000.000000  ...              1                 0
4  40.0  63777.777778  ...              0                 1
5  35.0  58000.000000  ...              0                 1
6  44.0  52000.000000  ...              1                 0
7  48.0  79000.000000  ...              0                 1
8  50.0  83000.000000  ...              0                 0
9  37.0  67000.000000  ...              0                 1

[10 rows x 6 columns]

# **Step 6: Splitting the datasets into training sets and Test sets**

In [20]:
encoded_data

Age        Salary  ...  Country_Spain  purchased_status
0  44.0  72000.000000  ...              0                 0
1  27.0  48000.000000  ...              1                 1
2  30.0  54000.000000  ...              0                 0
3  38.0  61000.000000  ...              1                 0
4  40.0  63777.777778  ...              0                 1
5  35.0  58000.000000  ...              0                 1
6  44.0  52000.000000  ...              1                 0
7  48.0  79000.000000  ...              0                 1
8  50.0  83000.000000  ...              0                 0
9  37.0  67000.000000  ...              0                 1

[10 rows x 6 columns]

In [21]:
x_train, x_test, y_train, y_test = train_test_split(encoded_data[encoded_data.columns[:-1]].values, encoded_data['purchased_status'].values, test_size=0.25, random_state=0)

In [22]:
x_train

array([[3.7e+01, 6.7e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [2.7e+01, 4.8e+04, 0.0e+00, 0.0e+00, 1.0e+00],
       [4.4e+01, 5.2e+04, 0.0e+00, 0.0e+00, 1.0e+00],
       [4.8e+01, 7.9e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [3.8e+01, 6.1e+04, 0.0e+00, 0.0e+00, 1.0e+00],
       [4.4e+01, 7.2e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [3.5e+01, 5.8e+04, 1.0e+00, 0.0e+00, 0.0e+00]])

In [23]:
y_train

array([1, 1, 0, 1, 0, 0, 1])

In [24]:
x_test

array([[3.00000000e+01, 5.40000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [5.00000000e+01, 8.30000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [4.00000000e+01, 6.37777778e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00]])

In [25]:
y_test

array([0, 0, 1])

In [26]:
x_train.shape, x_test.shape

((7, 5), (3, 5))

# **Step 7: Feature Scaling**

In [27]:
normalizer = preprocessing.Normalizer()
normalized_train_X = normalizer.fit_transform(x_train)
normalized_train_X

array([[5.52238722e-04, 9.99999847e-01, 1.49253709e-05, 0.00000000e+00,
        0.00000000e+00],
       [5.62499911e-04, 9.99999842e-01, 0.00000000e+00, 0.00000000e+00,
        2.08333300e-05],
       [8.46153543e-04, 9.99999642e-01, 0.00000000e+00, 0.00000000e+00,
        1.92307623e-05],
       [6.07594825e-04, 9.99999815e-01, 1.26582255e-05, 0.00000000e+00,
        0.00000000e+00],
       [6.22950699e-04, 9.99999806e-01, 0.00000000e+00, 0.00000000e+00,
        1.63934394e-05],
       [6.11110997e-04, 9.99999813e-01, 1.38888863e-05, 0.00000000e+00,
        0.00000000e+00],
       [6.03448166e-04, 9.99999818e-01, 1.72413762e-05, 0.00000000e+00,
        0.00000000e+00]])

In [28]:
normalized_test_X = normalizer.fit_transform(x_test)
normalized_test_X

array([[5.55555470e-04, 9.99999846e-01, 0.00000000e+00, 1.85185157e-05,
        0.00000000e+00],
       [6.02409529e-04, 9.99999818e-01, 0.00000000e+00, 1.20481906e-05,
        0.00000000e+00],
       [6.27177577e-04, 9.99999803e-01, 0.00000000e+00, 1.56794394e-05,
        0.00000000e+00]])