<a href="https://colab.research.google.com/github/naveen2139/GUVI-DATA_SCIENCE_B9/blob/main/Random_Forest_Assignment16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Social_Network_Ads.csv

**Importing the libraries**

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import seaborn as sns
import warnings
from sklearn import preprocessing
%matplotlib inline

**Importing the dataset**

In [2]:
files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads.csv


{'Social_Network_Ads.csv': b'User ID,Gender,Age,EstimatedSalary,Purchased\r\n15624510,Male,19,19000,0\r\n15810944,Male,35,20000,0\r\n15668575,Female,26,43000,0\r\n15603246,Female,27,57000,0\r\n15804002,Male,19,76000,0\r\n15728773,Male,27,58000,0\r\n15598044,Female,27,84000,0\r\n15694829,Female,32,150000,1\r\n15600575,Male,25,33000,0\r\n15727311,Female,35,65000,0\r\n15570769,Female,26,80000,0\r\n15606274,Female,26,52000,0\r\n15746139,Male,20,86000,0\r\n15704987,Male,32,18000,0\r\n15628972,Male,18,82000,0\r\n15697686,Male,29,80000,0\r\n15733883,Male,47,25000,1\r\n15617482,Male,45,26000,1\r\n15704583,Male,46,28000,1\r\n15621083,Female,48,29000,1\r\n15649487,Male,45,22000,1\r\n15736760,Female,47,49000,1\r\n15714658,Male,48,41000,1\r\n15599081,Female,45,22000,1\r\n15705113,Male,46,23000,1\r\n15631159,Male,47,20000,1\r\n15792818,Male,49,28000,1\r\n15633531,Female,47,30000,1\r\n15744529,Male,29,43000,0\r\n15669656,Male,31,18000,0\r\n15581198,Male,31,74000,0\r\n15729054,Female,27,137000,1\r\n1

In [3]:
df=pd.read_csv("Social_Network_Ads.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
df.shape

(400, 5)

In [5]:
df.drop('User ID', axis=1, inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   EstimatedSalary  400 non-null    int64 
 3   Purchased        400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [7]:
#confirmation for null values
df.isna().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [8]:
df.Gender=df.Gender.str.lower()
df.Gender=df.Gender.str.strip()
df

Gender  Age  EstimatedSalary  Purchased
0      male   19            19000          0
1      male   35            20000          0
2    female   26            43000          0
3    female   27            57000          0
4      male   19            76000          0
..      ...  ...              ...        ...
395  female   46            41000          1
396    male   51            23000          1
397  female   50            20000          1
398    male   36            33000          0
399  female   49            36000          1

[400 rows x 4 columns]

In [9]:
df.Gender=df.Gender.map({'male':0,"female":1})
df

Gender  Age  EstimatedSalary  Purchased
0         0   19            19000          0
1         0   35            20000          0
2         1   26            43000          0
3         1   27            57000          0
4         0   19            76000          0
..      ...  ...              ...        ...
395       1   46            41000          1
396       0   51            23000          1
397       1   50            20000          1
398       0   36            33000          0
399       1   49            36000          1

[400 rows x 4 columns]

In [27]:
df.describe()

Gender         Age  EstimatedSalary   Purchased
count  400.000000  400.000000       400.000000  400.000000
mean     0.510000   37.655000     69742.500000    0.357500
std      0.500526   10.482877     34096.960282    0.479864
min      0.000000   18.000000     15000.000000    0.000000
25%      0.000000   29.750000     43000.000000    0.000000
50%      1.000000   37.000000     70000.000000    0.000000
75%      1.000000   46.000000     88000.000000    1.000000
max      1.000000   60.000000    150000.000000    1.000000

In [29]:
X = df.drop(['Purchased'], axis=1)

y = df['Purchased']

**Splitting the dataset into the Training set and Test set**

In [30]:
# split data into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [31]:
X_train.shape, X_test.shape

((268, 3), (132, 3))

**Feature Scaling**

In [35]:
normalizer = preprocessing.Normalizer()
normalized_train_X = normalizer.fit_transform(X_train)
normalized_train_X

array([[1.05263138e-05, 6.10526202e-04, 9.99999814e-01],
       [0.00000000e+00, 1.13636290e-03, 9.99999354e-01],
       [0.00000000e+00, 6.94915086e-04, 9.99999759e-01],
       [0.00000000e+00, 3.14606726e-04, 9.99999951e-01],
       [1.24999983e-05, 5.24999928e-04, 9.99999862e-01],
       [9.25925856e-06, 3.88888859e-04, 9.99999924e-01],
       [1.04166655e-05, 4.79166612e-04, 9.99999885e-01],
       [8.84955676e-06, 4.15929168e-04, 9.99999913e-01],
       [3.57142609e-05, 1.17857061e-03, 9.99999305e-01],
       [0.00000000e+00, 7.59999781e-04, 9.99999711e-01],
       [0.00000000e+00, 5.50561714e-04, 9.99999848e-01],
       [6.66665241e-05, 2.06666225e-03, 9.99997862e-01],
       [1.26582269e-05, 3.79746808e-04, 9.99999928e-01],
       [0.00000000e+00, 3.40425512e-04, 9.99999942e-01],
       [8.54700823e-06, 2.73504263e-04, 9.99999963e-01],
       [1.40845051e-05, 5.21126690e-04, 9.99999864e-01],
       [1.16279067e-05, 2.09302321e-04, 9.99999978e-01],
       [1.26582261e-05, 5.31645

In [37]:
normalized_test_X = normalizer.fit_transform(X_test)
normalized_test_X

array([[4.54544460e-05, 2.09090452e-03, 9.99997813e-01],
       [1.13636338e-05, 6.70454395e-04, 9.99999775e-01],
       [2.27272681e-05, 6.36363507e-04, 9.99999797e-01],
       [1.04166654e-05, 4.99999937e-04, 9.99999875e-01],
       [3.57142665e-05, 1.03571373e-03, 9.99999463e-01],
       [1.61290304e-05, 4.83870911e-04, 9.99999883e-01],
       [9.34579349e-06, 4.39252294e-04, 9.99999903e-01],
       [1.20481920e-05, 3.49397569e-04, 9.99999939e-01],
       [0.00000000e+00, 5.33333257e-04, 9.99999858e-01],
       [0.00000000e+00, 6.46153711e-04, 9.99999791e-01],
       [1.53846132e-05, 5.38461460e-04, 9.99999855e-01],
       [2.94117290e-05, 1.55882163e-03, 9.99998785e-01],
       [2.08333309e-05, 4.79166612e-04, 9.99999885e-01],
       [4.34782444e-05, 8.69564888e-04, 9.99999621e-01],
       [0.00000000e+00, 3.44827566e-04, 9.99999941e-01],
       [0.00000000e+00, 3.24074057e-04, 9.99999947e-01],
       [2.63157648e-05, 1.36841977e-03, 9.99999063e-01],
       [1.35135109e-05, 6.21621

**Fitting Random Forest to the Training set**

In [41]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state=0)

# fit the model to the training set

clf.fit(X_train, y_train)


Model accuracy score : 0.8939


**Predicting the Test set results**

In [45]:
# Predict on the test set results

y_pred = clf.predict(X_test)
y_pred


array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [44]:
# Check accuracy score 
from sklearn.metrics import accuracy_score

print('Model accuracy score : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score : 0.8939


Random Forest Classifier model with parameter n_estimators=500
:

In [48]:
rfc_100 = RandomForestClassifier(n_estimators=500, random_state=0)

# fit the model to the training set

rfc_100.fit(X_train, y_train)

# Predict on the test set results

y_pred_100 = rfc_100.predict(X_test)

# Check accuracy score 

print('Model accuracy score with 100 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))

Model accuracy score with 100 decision-trees : 0.9167


**Making the Confusion Matrix**

In [49]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[74  6]
 [ 8 44]]


**Visualising the Training set results**

**Visualising the Test set results**