# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [7]:
np.__version__

'1.20.1'

In [8]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/KIRAN/anaconda3\\Library\\include']


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [9]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [10]:
print("Size of array",null_vector.size)
print("Size of each element in Array",null_vector.itemsize)
print("Total memory size of Array",null_vector.size*null_vector.itemsize)

Size of array 10
Size of each element in Array 8
Total memory size of Array 80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
arange_vector=np.arange(10,50)
print(arange_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
print(arange_vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [15]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [16]:
temp_list=[1,2,0,0,4,0]
print(np.nonzero(temp_list))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [17]:
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [18]:
matrix=np.random.random((3,3,3))*100
print(matrix)

[[[10.4162525  45.38348104 56.05559888]
  [39.91162823 51.29569863  5.81085892]
  [43.88448792 81.44324036 22.37400489]]

 [[11.22987477 49.54081941 95.20340997]
  [74.12647279 86.5872658  88.48609374]
  [47.98342032 18.06936117 13.48645458]]

 [[89.88085734 88.69078187 63.21816966]
  [75.84953533 60.30057234 28.50041764]
  [59.89606186 21.48899817  5.62375385]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [19]:
matrix=np.random.random((10,10))
print(matrix)
print("\nMinimum value in matrix : ",matrix.min())
print("Maximum value in matrix : ",matrix.max())

[[0.24214108 0.1100284  0.92416222 0.50348269 0.82521944 0.12611676
  0.40171536 0.5116356  0.22661173 0.56652188]
 [0.67769539 0.87446936 0.83682701 0.75968951 0.56280239 0.75375565
  0.43631347 0.88797405 0.27346597 0.04771107]
 [0.95014046 0.30186799 0.91971041 0.17413729 0.63845958 0.23004446
  0.34790502 0.04181736 0.88310374 0.66244025]
 [0.76907221 0.57400476 0.51794674 0.52624115 0.34492243 0.61600589
  0.95160817 0.81980296 0.59616544 0.07901023]
 [0.26010792 0.7756819  0.16384974 0.33016029 0.03207092 0.76077994
  0.38893364 0.67058575 0.73285507 0.38433917]
 [0.40897114 0.48652007 0.72314375 0.94661775 0.33430679 0.01918508
  0.93759859 0.03872637 0.35457592 0.79382954]
 [0.17487307 0.93550309 0.01951832 0.83870146 0.30229277 0.47283052
  0.0568256  0.24830705 0.95808556 0.45164802]
 [0.04301329 0.53087284 0.92859677 0.10073939 0.94971671 0.45182488
  0.33263803 0.6152135  0.91440657 0.85777496]
 [0.13829124 0.04197533 0.18613916 0.28889346 0.55427234 0.25376269
  0.34674002

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [20]:
matrix=np.random.random(30)
print(matrix)
print("\n Mean value : ",matrix.mean())

[0.68342287 0.8842677  0.08152317 0.43642749 0.51948475 0.91227567
 0.98165118 0.38466503 0.23878467 0.08529669 0.55361455 0.63703847
 0.4225596  0.68786621 0.93107225 0.24089712 0.47486522 0.86583968
 0.27778307 0.99814113 0.66503563 0.86316704 0.51371608 0.43866668
 0.77571361 0.47633454 0.54328733 0.30031119 0.32179537 0.53886121]

 Mean value :  0.5578121723941734


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [21]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [27]:
orr = np.ones((3,3))
orr = np.pad(orr, pad_width=1, mode='constant', constant_values=0)
orr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [30]:
0 * np.nan


nan

In [31]:
np.nan == np.nan


False

In [32]:
np.inf > np.nan


False

In [33]:
np.nan - np.nan


nan

In [34]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [35]:
arr=np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [36]:
arr=np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [37]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [38]:
arr=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [39]:
arr=np.random.random((5,5))
arrMax,arrMin=arr.max(),arr.min()
arr=(arr-arrMin)/(arrMax-arrMin)
arr

array([[0.29197947, 0.61317822, 0.48707453, 0.        , 0.16429578],
       [0.04332598, 0.94230913, 0.68551841, 0.52915282, 0.85145431],
       [0.28723863, 0.47471863, 0.10176555, 0.87273808, 0.63547125],
       [0.05245736, 0.45934098, 0.48317829, 0.14621066, 0.40670275],
       [0.50728035, 0.31805542, 0.56564078, 1.        , 0.43351586]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [41]:
color = np.dtype([('r', np.ubyte, 1),
                  ('g', np.ubyte, 1),
                  ('b', np.ubyte, 1),
                  ('a', np.ubyte, 1)])
color

<ipython-input-41-1a5614d30f02>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [42]:
srr = np.dot(np.ones((5,3)), np.ones((3,2)))
srr

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [43]:
z = np.arange(11)
z 
z[(3<z) & (z <= 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [76]:
z=np.arange(1,10,2)
print(z)

[1 3 5 7 9]


In [77]:
z**z
#Legal

array([        1,        27,      3125,    823543, 387420489], dtype=int32)

In [78]:
2 << Z >> 2
#Legal

array([  0,   2,   8,  32, 128], dtype=int32)

In [79]:
Z <- Z
#Legal

array([False, False, False, False, False])

In [80]:
1j*Z
#Legal

array([0.+0.j, 0.+2.j, 0.+4.j, 0.+6.j, 0.+8.j])

In [81]:
Z/1/1
#Legal

array([0., 2., 4., 6., 8.])

In [82]:
Z<Z>Z
#Illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [83]:
np.array(0) / np.array(0)

<ipython-input-83-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [84]:
np.array(0) // np.array(0)

<ipython-input-84-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [85]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [86]:
Z = np.arange(-10, 10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-10.   0.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [109]:
Z = np.arange(1,10)
Z1 = np.arange(1,10,2)
np.intersect1d(Z,Z1)

array([1, 3, 5, 7, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [114]:
np.seterr(all="ignore")
np.array(0) // np.array(0)

0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [115]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [124]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(today)
print(yesterday)
print(tomorrow)

2021-08-14
2021-08-13
2021-08-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [125]:
np.arange('2016-07','2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [126]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out =B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.divide(A,B, out=A)

array([-0.16666667, -0.16666667, -0.16666667])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [127]:
A = np.random.uniform(0, 10, 10)
A - A%1
np.floor(A)
np.ceil(A)-1


array([0., 0., 4., 7., 9., 1., 5., 4., 9., 4.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [128]:
S = np.zeros((5,5))
S += np.arange(5)
S

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [129]:
def generate():
    for x in range (10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [130]:
X = np.linspace(0,1,11,endpoint=False)[1:]
X

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [134]:
arr=np.random.random(10)*1000
print("Before sort")
print(arr)
arr.sort()
print("After sort")
print(arr)

Before sort
[ 25.27522941  83.966085   499.82772399 235.56087742 886.994469
 453.32739489   8.09676634 466.68379497 640.45738498 186.02819428]
After sort
[  8.09676634  25.27522941  83.966085   186.02819428 235.56087742
 453.32739489 466.68379497 499.82772399 640.45738498 886.994469  ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [135]:
np.add.reduce(arr)

3486.2179202912785

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [138]:
arr1=np.random.random(10)*1000
arr2=np.random.random(10)*1000
print("arr1:",arr1)
print("arr2:",arr2)
np.allclose(arr1,arr2)

arr1: [567.72175149 345.87815713 135.69679476 754.70787123 664.64687657
 262.44518832 983.68308276 935.38830169 599.23965135 312.48684997]
arr2: [411.41067372 909.07702424 928.541149   905.2064877  545.69682489
 530.50101041 982.24375929 171.81623059 208.37224335 741.69689206]


False

In [139]:
np.array_equal(arr1,arr2)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [140]:
X = np.zeros(10)
X.flags.writeable = False
X[0] = True

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [141]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**0.5, Y**0.5)
Q = np.arctan2(X,Y)
print(R)
print(Q)

[0.87046001 0.85089132 0.77682659 0.7245394  0.50959179 0.55195698
 0.94919666 0.78014896 0.74286939 0.34261303]
[1.53857569 0.70245613 0.73876056 0.29617188 0.13168176 0.1034988
 0.9752966  0.71528784 0.52266862 0.0160323 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [142]:
z = np.zeros((5,5), [('x', float), ('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [143]:
x = np.arange(8)
y = x + 0.5
c = 1.0/np.subtract.outer(x,y)
np.linalg.det(c)

3638.1636371179666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [144]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [145]:
np.set_printoptions(threshold=1)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [146]:
x = np.arange(100)
c = np.random.uniform(0,100)
index = (np.abs(x-c)).argmin()
print(x[index])

90


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [147]:
z = np.zeros(10, [('position', [('x',float, 1),
                                ('y',float, 1)]),
                  ('color',    [ ('r', float, 1),
                                 ('g', float, 1),
                                 ('b', float, 1)])])
z

<ipython-input-147-f7cbdb917100>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z = np.zeros(10, [('position', [('x',float, 1),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ..., ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [148]:
import scipy
import scipy.spatial
z = np.random.random((100,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.56548037 0.52445189 ... 0.20035132 0.12721782 0.7066309 ]
 [0.56548037 0.         0.04189695 ... 0.37028044 0.43836565 0.63360275]
 [0.52445189 0.04189695 0.         ... 0.32860839 0.39745265 0.63002417]
 ...
 [0.20035132 0.37028044 0.32860839 ... 0.         0.08100149 0.66176202]
 [0.12721782 0.43836565 0.39745265 ... 0.08100149 0.         0.64512009]
 [0.7066309  0.63360275 0.63002417 ... 0.66176202 0.64512009 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [149]:
z = np.arange(10, dtype=np.float32)
z = z.astype(np.int32, copy = False)
z

array([0, 1, 2, ..., 7, 8, 9])

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [150]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
        6,  ,  , 7, 8\n
         ,  , 9,10,11\n""")
c = np.genfromtxt(s, delimiter=",", dtype=np.int)
c

<ipython-input-150-dc28d0cc3cfc>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c = np.genfromtxt(s, delimiter=",", dtype=np.int)


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [151]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [152]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
t = np.exp(-( (d - mu)/(2.0 * sigma**2)))
print(t)

[[0.49306869 0.53076772 0.56440712 ... 0.56440712 0.53076772 0.49306869]
 [0.53076772 0.576966   0.62007989 ... 0.62007989 0.576966   0.53076772]
 [0.56440712 0.62007989 0.67513872 ... 0.67513872 0.62007989 0.56440712]
 ...
 [0.56440712 0.62007989 0.67513872 ... 0.67513872 0.62007989 0.56440712]
 [0.53076772 0.576966   0.62007989 ... 0.62007989 0.576966   0.53076772]
 [0.49306869 0.53076772 0.56440712 ... 0.56440712 0.53076772 0.49306869]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [153]:
n = 10
p = 3 
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
print(z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [154]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1, keepdims=True)
y

array([[ 0.30293941, -0.11207224,  0.35325805, ...,  0.09231647,
        -0.18129987,  0.1339714 ],
       [ 0.07843254, -0.120042  ,  0.0827954 , ..., -0.1417096 ,
         0.41738357,  0.31122399],
       [ 0.14710583, -0.0504987 , -0.28730205, ..., -0.02907925,
         0.30456858,  0.28147743],
       [ 0.02111226,  0.31120452, -0.235378  , ..., -0.33913179,
         0.37363574,  0.18867271],
       [ 0.34582668,  0.42877019,  0.26820089, ..., -0.08111718,
        -0.06920349, -0.1096218 ]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [155]:
e = np.random.randint(0,10,(3,3))
e[e[:,1].argsort()]
e

array([[5, 8, 8],
       [3, 8, 5],
       [0, 9, 9]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [156]:
q = np.random.randint(0,3,(3,10))
~(q.any(axis=0)).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [157]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
m

0.43499052356079737

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [158]:
x = np.arange(3).reshape(1,3)
y = np.arange(3).reshape(3,1)
it = np.nditer([x,y,None])
for x,y,z in it: z[...] = x + y
it.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [159]:
class ArrayClass:
    name="Temp"
print(ArrayClass.name)

Temp


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [160]:
arr1=np.random.random((5,5,3))
arr2=np.random.random((5,5))
print(arr1,end="\n")
print(arr2,end="\n")
print(arr1*arr2)

[[[0.70846019 0.93043027 0.95522096]
  [0.42317863 0.91577189 0.79661529]
  [0.1168736  0.25126645 0.51792599]
  [0.34245828 0.71417683 0.65075831]
  [0.39541605 0.98524783 0.92249231]]

 [[0.41913874 0.66834775 0.968701  ]
  [0.77533914 0.96614582 0.88880732]
  [0.71442497 0.91716063 0.63578675]
  [0.47916224 0.27028106 0.26338753]
  [0.636838   0.85999852 0.67336105]]

 [[0.16822223 0.08696172 0.9119003 ]
  [0.88251419 0.47570815 0.14694923]
  [0.41234416 0.37377326 0.42350372]
  [0.63169754 0.98766705 0.61495714]
  [0.28690561 0.4218601  0.30760071]]

 [[0.71938725 0.15864619 0.19104216]
  [0.84216331 0.68146811 0.84184164]
  [0.80526175 0.25795168 0.60899371]
  [0.64060576 0.09873574 0.39327671]
  [0.07200006 0.17872391 0.39603584]]

 [[0.19029798 0.54480297 0.34589236]
  [0.94880305 0.88561847 0.27111445]
  [0.20740013 0.48548998 0.4030823 ]
  [0.41749168 0.03206825 0.54455678]
  [0.56432007 0.02148757 0.58911789]]]
[[0.02759171 0.69061301 0.52069316 0.12007391 0.4218277 ]
 [0.499

ValueError: operands could not be broadcast together with shapes (5,5,3) (5,5) 

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [167]:
arr=np.random.random((5,5))
print(arr)
arr[[0, 2]] = arr[[2, 0]]
print(arr)

[[0.83333361 0.99496802 0.51735515 0.55062733 0.36991242]
 [0.76635777 0.81950301 0.98545877 0.30423788 0.32986863]
 [0.35220667 0.90233777 0.98254276 0.7744536  0.24629563]
 [0.05641717 0.06231581 0.92692645 0.89233885 0.76142792]
 [0.71206583 0.77971541 0.35422935 0.69221277 0.22516622]]
[[0.35220667 0.90233777 0.98254276 0.7744536  0.24629563]
 [0.76635777 0.81950301 0.98545877 0.30423788 0.32986863]
 [0.83333361 0.99496802 0.51735515 0.55062733 0.36991242]
 [0.05641717 0.06231581 0.92692645 0.89233885 0.76142792]
 [0.71206583 0.77971541 0.35422935 0.69221277 0.22516622]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)